### ISSUE TITLE
change fields' format

### ISSUE THREAD

**Issue by grant-guo** [kids-first/kf-es-model#21]
In both `file_centric` and `participant_centric`, make the fields changes as the following:

* change the format of `size` field to `long`
* change all of the timestamp format from `yyyy-MM-dd HH:mm:ss.SSSSSS||yyyy-MM-dd HH:mm:ss` to `yyyy-MM-dd HH:mm:ss.SSSSSS||yyyy-MM-dd HH:mm:ss||yyyy-MM-dd'T'HH:mm:ss.SSSSSS+HH:mm`

**Comment by junjun-zhang** [comment]
addressed by #23
